### ISSUE TITLE
TiProxy tracking issue

### ISSUE THREAD

**Issue by xhebox** [pingcap/TiProxy#7]
## Development Task

The current architecture is unreasonable.

- [ ] configuration
  - #1
  - #56
  - #43
  - #46
  - security maybe
  - #88
- [x] #11 We have a simpler way to manage namespace after introducing etcd
- [ ] #14 Simple alternative implementation
- [ ] #15 Get namespace routing working again
- [x] #8 As a standalone component, we should be decoupled from TiDB as much as possible: be general, be simple, be stupid.
- [ ] Refactor router to smaller components
  -  We could split router to `observer` and `checker`. Checker can be health checker or rebalance checker. Functionality of router can be done robustly with much less code. This needs the factor of namespace manager and a clean server.
- [x] #23
- [x] #69
 
Misc PRs:

- [x] #2
- [x] #3 
- [x] #4
- [x] #5 
- [x] #6
- [x] #63
